### ISSUE TITLE
Reverse Shutter Direction

### ISSUE THREAD

**Issue by fab301s** [howm/homebridge-rfx-shutter#110]
I use this plugin to control an awning however the direction of travel is the opposite of what it needs to be.

In order to get around this I’ve modified a line of code in `ShutterAccessories.js` from `rfxcom_1.fireShutterAction(this.deviceId, up ? rfxcom_1.ShutterAction.UP : rfxcom_1.ShutterAction.DOWN);` to
`rfxcom_1.fireShutterAction(this.deviceId, up ? rfxcom_1.ShutterAction.DOWN : rfxcom_1.ShutterAction.UP);`

Is it possible to add something to the configuration to allow this to be changed without the need to modify code after each update?

**Comment by momsse** [comment]
Hi @fab301s,

The following PR should achieve that: https://github.com/howm/homebridge-rfx-shutter/pull/111 using an addition `direction` option that need to be set to `reverse`.

Will try to test those changes IRL when I will have some time and then release if all is good.

**Comment by fab301s** [comment]
Fantastic thank you!

**Comment by momsse** [comment]
@fab301s tested with my somfy shutters. Changes are published on `2.1.0` version

**Comment by fab301s** [comment]
Thank you!

Unfortunately under my testing the configuration of either `Normal` or `Reverse` does not appear to make a difference.  The outcome is the same.

Here is my config

```
{
    "platform": "RFXShutterDynamicPlatform",
    "tty": "/dev/tty.usbserial-XXXXXXXX",
    "name": "Awning",
    "deviceId": "0x0FFA00/1",
    "openSeconds": 30,
    "closeSeconds": 30,
    "direction": "reverse"
}
```

**Comment by fab301s** [comment]
Working great, thanks!
