### ISSUE TITLE
Don't show any shutter

### ISSUE THREAD

**Issue by phis5533** [howm/homebridge-rfx-shutter#25]
Hello I've just setup the v2 as a platform, but no shutter are detected.
Can I configure my config.json to force them, just like in the v1 ?

Here is my config : 

`
{
        "bridge": {
                "name": "Homebridge RFXCom",
                "username": "XXXXXXXXXX",
                "pin": "XXXXXXXXX"
        },

        "description": "HomeBridge RFXCom",

        "selectiveLoad": true,

        "plugins":  [
                "homebridge-rfx-shutter"
                 ],

        "platform": [

        {
                "platform": "RFXShutterDynamicPlatform",
                "tty": "/dev/tty.usbserial-A12HRIVN"
        }
        ]

}
`

And here is my log file : no issues... 

`[8/29/2020, 10:49:36 AM] Loaded config.json with 0 accessories and 0 platforms.
[8/29/2020, 10:49:36 AM] ---
[8/29/2020, 10:49:38 AM] Loaded plugin: homebridge-rfx-shutter@2.0.2
[8/29/2020, 10:49:38 AM] Registering platform 'homebridge-rfx-shutter.RFXShutterDynamicPlatform'
[8/29/2020, 10:49:38 AM] ---
Setup Payload:
X-HM://0023QQRSL9IFP
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXXXXXX │     
    └────────────┘     
                       
[8/29/2020, 10:49:38 AM] Homebridge is running on port 62624.

`

Any help welcome :-) !

Thx for your job !

**Comment by momsse** [comment]
First very sorry for the bad delay. I didn't turn on issue notifications.

Did you finally manage with this issue ?

It seems a communication issue with the transceiver since there is no log at all of https://github.com/rfxcom/node-rfxcom

**Comment by phis5533** [comment]
Hi,

thank you for your answers, I'm using another plugin now to manage my DiO and my RFY together.
it is homebridge-rfxtrx
BR,
Philippe

**Comment by phis5533** [comment]
Let it closed.
Thx
