### ISSUE TITLE
feature request : naming of shutter

### ISSUE THREAD

**Issue by glefand** [howm/homebridge-rfx-shutter#27]
Hi,

as the shutter are automatically discovered, is it possible to asssociate a name instead of the 0x12345/1 id ?

Best Regards,
Guillaume

**Comment by phis5533** [comment]
Hello @glefand ,

you mean auto discover does work for you ? 
can you post your config file please ?
As I've mentioned in my post, it doesn't work for me and I don't understand why... 
Thank you 
BR

Philippe

**Comment by momsse** [comment]
@glefand you can update the name directly from the Homebridge app. This need to be done only once (plugin restart will not rename them with the techy ones)

@phis5533 if you still have those issue I will try to help you here => https://github.com/howm/homebridge-rfx-shutter/issues/25
