### ISSUE TITLE
feature request : prog script

### ISSUE THREAD

**Issue by glefand** [howm/homebridge-rfx-shutter#28]
Hi,

Is it possible to add a simple script to program a new shutter ? (CLI should be enough)

Best Regards,
Guillaume

**Comment by momsse** [comment]
First very sorry for the bad delay. I didn't turn on issue notifications.

Can you explain a little more about what you mean by "program a new shutter" ?

**Comment by glefand** [comment]
Hi,
the idea is to add a script in the node js package which allow to send a "program" command with the id 0x12345.
this is to store the new shutter id in the RFX433xl without having to use the rfxcom windows program. I have a raspberry and mac, I don't have windows, and to perfrom the first "install", I had to use a windows virtualized to install the rfxcom program to set my shutter.
here we could do it directly on the raspberry CLI by sending the right command.

**Comment by momsse** [comment]
Ok i thing I get it. I used the RFXcom plugin for Jeedom for doing that job long time ago. I completely forgot that "program" part 😅

If you are confortable enough doing it I will integrate your pull request on the project. I suggest to put it on a `scripts` and add some lines on the readme about it.

**Comment by glefand** [comment]
Great ! thanks
