### ISSUE TITLE
Update according to NodeJS

### ISSUE THREAD

**Issue by phis5533** [howm/homebridge-rfx-shutter#293]
Hello,

first, many thanks for your job that I use every day !

I've tried to update NodeJS, from v.16 to the last v.18, and then I obtain an error while launching Homebridge : 

```
[11/29/2022, 8:37:50 AM] ERROR LOADING PLUGIN homebridge-rfx-shutter:
[11/29/2022, 8:37:50 AM] Error: The module '/usr/local/lib/node_modules/homebridge-rfx-shutter/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```

Seems that the plugin needs a compilation update.
Do you think it is possible on your side ?

Thank you.
Have a nice day
Regards,

Philippe

**Comment by momsse** [comment]
Hi @phis5533 

Bump the project node version to 18 (https://github.com/howm/homebridge-rfx-shutter/pull/295) but that should not help you since the error seems to be related to the transitive package `@serialport/bindings`. Seems to be a mix of package install with different node versions but unsure TBH

**Comment by fab301s** [comment]
Wanted to echo the sentiment and say thanks for the plugin!

I’m still running NodeJS v16, but in time will need to move to v18.

Watching this with interest 🙂

**Comment by phis5533** [comment]
Hello,
I'm not sure to understand, it's the `@serialport/bindings` which needs to be updated ?

Thx for your time

**Comment by JurgenLB** [comment]
For reference
`npm install -g agentkeepalive --save`
`npm install -g http-proxy-agent --save`
`npm install -g https-proxy-agent --save`
`npm install -g socks-proxy-agent --save`
`npm rebuild`
has solved this for me.
my system ;
Debian GNU/Linux Bullseye (11)
Node.JS            v18.19.0
Homebridge UI v4.55.1
Homebridge.     v1.7.0

**Comment by phis5533** [comment]
Thanks a lot for your information sharing !
