### ISSUE TITLE
Somfy remote

### ISSUE THREAD

**Issue by flinti0402** [howm/homebridge-rfx-shutter#38]
Hi,

first of all thanks for your code. I have a question regarding V. 2

The different shutters are found with the names described in the readme. Strange is that I see multiple instances for the same device, e.g. my Id is x010101/1 discovery shows x010101/2 x010101/3 up to 4.

As I have multiple remotes and shutters I need to be able to handle different times for closing and opening. So ideal would be having this for any Somfy shutter.

I I try to use the config for version 1, I got errors, when I try to start homebridge, "peer dependency is missing..."

Any comment on that ?

Regards

**Comment by momsse** [comment]
First very sorry for the bad delay. I didn't turn on issue notifications.

> The different shutters are found with the names described in the readme. Strange is that I see multiple instances for the same device, e.g. my Id is x010101/1 discovery shows x010101/2 x010101/3 up to 4.

I didn't encountered this issue but you can use `excludedDeviceIds` to exclude any extra instances of the instance.

> As I have multiple remotes and shutters I need to be able to handle different times for closing and opening. So ideal would be having this for any Somfy shutter.

`v2.x.x` simplified a lot the plugin but I plan to add something equivalent to the `v1.x.x` for fine tuning the up/down delay by shutter (open to pull requests btw).

> I I try to use the config for version 1, I got errors, when I try to start homebridge, "peer dependency is missing..."

Absolutely no clue about this one sorry :/
