### ISSUE TITLE
other protocol

### ISSUE THREAD

**Issue by phis5533** [howm/homebridge-rfx-shutter#51]
Helle @momsse,

first of all, many thanks for your job !

Nevertheless, I've got a request.
I believe your plugin "read" into the RFXCom what remote-control is recorded inside.
It does work for protocol such as RFY, which work very well for me by the way.
But for another protocol : Blinds1 / BLIND_T17, the RFXmngr doesn't write anything into the device, it just transmit close/open/stop order.
My question is simple : can you implement that behavior in your plugin ? It will then appear in Home.app as 3 switch open/stop/close ?
Or maybe I missed something and it is already available ? 

Thank you.
BR,
Philippe

**Comment by momsse** [comment]
Hi @phis5533,

Yes that's accurate, just listing "remotes" and then sending to them very basic `UP`/`DOWN` /`STOP` commands using sleep to approximately simulate the opening percentage of the shutter.

I would loved support more shutters protocols but without having some shutters using them (I use Somfy french brand ones) I can't do that much unfortunately :/

BTW, if you want to integrate any pull request that will support your shutters with generic enough code to work with both protocols y're welcome

Best,
